---
title: "SIR and mask"
output:
  pdf_document: 
    includes:
      in_header: header.tex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
pacman::p_load(tidyverse)
```

## Basic idea

- Simple SIR model disease progression with strata for mask-wearing status, resulting in compartments for S-masked, S-no mask, I-masked, I-no mask, R-masked, R-no mask.
- Supposing wearing a mask reduces both susceptibility and infectiousness (depending on who is wearing it)
- Assume transitions between masked-not masked based on social influence and fear of disease (noting FD type "infection" structure for fear of disease, when could actually be more about absolute number/density dependence -- interesting question to explore how structure affects dynamics)
- Work in proportions such that $S + I + R = 1$.  Similarly, $M + N = 1$.
- I am thinking of this as two distinct (but coupled) models on the same population.
- no demography
- Han2021 - Effects of masks on the transmission of infectious diseases.  Similar approach
- Del Valle 2012 - Modeling the Impact of Behavior Changes on the Spread of Pandemic Influenza: They do essentially the same model as I do, however they suggest a simpler transition for behaviour based off of a simple step function.  They also investigate a large scale agent-based model (approx 20mil agents I think).

## Where to go

- My model acts as an extension of Perra 2013 and De Valle 2012.  Their models are recoverable by changing the $\alpha$ and $\omega$ parameters.
- Social exhaustion is also something I might consider.
- customise $\alpha$ and $\omega$ to each SIR class
- Can compare current "fear + social" model, TPB model, and HBM.  Make for a long, but comparative piece.
- Incorporate behaviour burn out?
- Incorporate sub-classes with "always behaving" in certain way
- include reactance to behaviours, i.e. when it gets too much people blow up and refuse
- Include burn-out of behaviour, first steps towards a constant exit rate from behaviour.

## State diagram

\begin{center}
\begin{tikzpicture}[node distance=2cm and 1cm,>=stealth',auto, every place/.style={draw}]
    
    \node [place] (Sm) [text width=0.75cm, align=center] {$S_M$};
    \node [place] (Sn) [text width=0.75cm, align=center, below=of Sm] {$S_{N}$};
    \node [place] (Im) [text width=0.75cm, align=center, node distance=2.5cm,right=of Sm] {$I_M$};
    \node [place] (In) [text width=0.75cm, align=center, below=of Im] {$I_{N}$};
    \node[place] (Rm) [text width=0.75cm, align=center, node distance=2.5cm, right=of Im] {$R_M$};
    \node[place] (Rn) [text width=0.75cm, align=center, below=of Rm] {$R_N$};
    
    \draw[green,thick,dotted] ($(Sm.north west)+(-0.3,0.6)$)  rectangle ($(Rm.south east)+(0.3,-0.6)$);
    \draw[red,thick,dotted] ($(Sn.north west)+(-0.3,0.6)$)  rectangle ($(Rn.south east)+(0.3,-0.6)$);
    
    \node[green] (masks) at ($(Rm.north east)+(1,0.6)$) {\textbf{Masks}};
    \node[red] (nomasks) at ($(Rn.south east)+(1.3,-0.6)$) {\textbf{No Masks}};
    
    
    \path[->] (Sm) edge [bend left] node {$\alpha(t)$} (Sn);
    \path[->] (Sn) edge [bend left] node {$\omega(t)$} (Sm);
    \path[->] (Im) edge [bend left] node {$\alpha(t)$} (In);
    \path[->] (In) edge [bend left] node {$\omega(t)$} (Im);
    \path[->] (Rm) edge [bend left] node {$\alpha(t)$} (Rn);
    \path[->] (Rn) edge [bend left] node {$\omega(t)$} (Rm);
    
    \path[->] (Sm) edge node {$\lambda(t)$} (Im);
    \path[->] (Sn) edge node {$\lambda(t)$} (In);
    \path[->] (In) edge node {$\gamma$} (Rn);
    \path[->] (Im) edge node {$\gamma$} (Rm);

\end{tikzpicture}
\end{center}

## Parameter description


- $\lambda$ is the force of infection, assuming a form of FD
- $\frac{1}{\gamma}$ is average infectious period
- $\alpha$ is transition rate from wearing a mask to not wearing a mask
- $\omega$ is transition rate from not wearing a mask to wearing a mask
- $\nu$ is the waning immunity term

Further parameters that will pop up

- $\beta$ is the transmission rate
- $c$ is the reduction in chance of catching disease if S is wearing a mask # this description is inconsistent with code comment definition and `1-c` model structure (I think)
- $p$ is the reduction in chance of spreading disease if I is wearing a mask # this description is inconsistent with code comment definition and `1-p` model structure (I think)
- $\alpha_1$ is the rate of transition to no mask based on social influence of no mask
- $\alpha_2$ is the rate of transition to no mask based on fear of disease
- $\omega_1$ is the rate of transition to mask based on social influence of  mask
- $\omega_2$ is the rate of transition to no mask based on fear of disease


## Basic system of ODEs

$$
  \begin{aligned}
    \dot{S}_{M} & =  -\lambda(t) (1-c) S_{M} - \alpha(t) S_{M} + \omega(t) S_{N} + \nu R_M\\
    \dot{S}_{N} & =  -\lambda(t) S_{N} + \alpha(t) S_{M} - \omega(t) S_{N} + \nu R_N\\
    \dot{I}_{M} & = \lambda(t) (1-c) S_{M} - \alpha(t) I_{M} + \omega(t) I_{N} - \gamma I_{M}\\
    \dot{I}_{N} & = \lambda(t) S_{N} + \alpha(t) I_{M} - \omega(t) I_{N} - \gamma I_{N}\\
    \dot{R}_M & = \gamma I_{M}  - \alpha(t) R_{M} + \omega(t) R_{N} - \nu R_M\, \\
    \dot{R}_N & = \gamma I_{N} + \alpha(t) R_{M} - \omega(t) R_{N} - \nu R_N \, ,
  \end{aligned}
$$

where

$$
  \begin{aligned}
    \lambda(t) & = \beta \left( I_{N} + (1-p) I_M \right)\\
    \omega(t) & = \omega_1 (S_M + I_M + R_M) + \omega_2(I_M + I_{N}) + \omega_3\\
    \alpha(t) & = \alpha_1 (S_{N} + I_{N} + R_N) + \alpha_2(1 - (I_M + I_{N})) + \alpha_3\, .\\
  \end{aligned}
$$

## Disease-free equilibrium of the behaviour

**Case when $\omega_3 + \alpha_2 + \alpha_3 = 0$ and case when those equal 0 and $\omega_2 \neq 0$**.

The disease-free equilibrium of the behaviour $(M^*, N^*)$ is

$$
  (1 - \Delta, \Delta)
$$

where

$$
\Delta =
  \begin{cases}
    \frac{(\omega_1 - \alpha_1 + \omega_3 + \alpha_2 + \alpha_3) - \sqrt{(\omega_1 - \alpha_1 + \omega_3 + \alpha_2 + \alpha_3)^2 - 4(\omega_1 - \alpha_1)(\alpha_2 + \alpha_3)}}{2(\omega_1 - \alpha_1)} & \text{ if } \omega_1 - \alpha_1\neq 0\,, \\
    \frac{\alpha_2 + \alpha_3}{\omega_3 + \alpha_2 + \alpha_3} & \text{ else.}
  \end{cases}
$$

**Proof**:

Considering $N = S_N + I_N + R_N$, we can write

$$
  \dot{N} = -\omega(t) N + \alpha(t) M\, .
$$

In the disease-free equilibrium, $I_N = I_M = 0$, so this reduces to

$$
  \dot{N} = -(\omega_1 M + \omega_3) N + (\alpha_1N + (\alpha_2 + \alpha_3)) M\, .
$$

Using $M + N = 1$, we can reduce this to 

$$
  \dot{N} = cN^2 - (c + k) N + (k - \omega_3)\,
$$
where $c = (\omega_1 - \alpha_1)$ and $k = \alpha_2 + \alpha_3 + \omega_3$.  Equating $\dot{N} = 0$, we need to consider two situations.  First, when $c = 0$ we get

$$
  N = \frac{k - \omega_3}{k}\, .
$$

Second, when $c \neq 0$ (and using $0\leq N \leq 1$) we solve the quadratic equation to get

$$
  N = \frac{(c + k) - \sqrt{(c + k)^2 - 4c(k - \omega_3)}}{2c}\, .
$$

Subbing in $c$ and $k$ gets the result.

**NOTE**: Due to the constraint that parameters are positive, we find that no combination of $c, k, \omega_3$ can lead to $N$ being undefined.



## Next generation matrix

- The disease states are $I_M$ and $I_N$
- Cannot ignore $S_M$ and $S_N$!
- THIS NEEDS TO BE REDONE

The flow in is

$$
  \mathscr{F} = 
    \begin{bmatrix}
        \beta (1-c)\left( I_{N} + (1-p) I_M \right) S_M\\
        \beta \left( I_{N} + (1-p) I_M \right) S_N 
    \end{bmatrix}
$$

and flow out is

$$
  \mathscr{V} = 
    \begin{bmatrix}
        - \omega I_{N} + (\alpha + \gamma) I_{M} \\
        (\omega + \gamma) I_N -  \alpha I_{M}
    \end{bmatrix}\, .
$$

The differential of these with respect to the disease states (remembering that $\alpha$ and $\omega$ depend on $I_N$ and $I_M$) are:

$$
\begin{aligned}
  F &= 
    \begin{bmatrix}
      \beta(1-c)(1-p)S_M & \beta(1-c)S_M\\
      \beta(1-p)S_N & \beta S_N
    \end{bmatrix}\, , \\[1em]
  V &= 
    \begin{bmatrix}
      \gamma + \alpha - \alpha_2 I_M - (\omega_1 + \omega_2) I_N & (\alpha_1 - \alpha_2) I_M - \omega - \omega_2 I_N \\
      (\omega_1 + \omega_2) I_N - \alpha + \alpha_2 I_M & \gamma - (\alpha_1 - \alpha_2) I_M + \omega + \omega_2 I_N
    \end{bmatrix} \, .
\end{aligned}
$$

Then $R(t) = \sigma(t)$ where $\sigma(t)$ is the largest (absolute) eigenvalue of $(FV^{-1})(t)$.  Defining

* $x = \alpha - \alpha_2 I_M - (\omega_1 + \omega_2) I_N$, (rate of change in $I_M$ due to mask transitions)
* $y = \omega - (\alpha_1 - \alpha_2) I_M + \omega_2 I_N$, (rate of change in $I_N$ due to mask transitions)
* $a = (1 - p)(\gamma + y) + x$, (total rate of change in $I_N$ accounting for reduced infections due to mask ($1-p$)?)
* $b = (1 - p)y + \gamma + x$, and (total rate of change in $I_M$ accounting for reduced infections due to mask ($1-p$)?)
* $\Gamma = \frac{\beta}{\gamma(\gamma + x + y)}$ ($R_0$ with no mask effects ($p = c = 0$))

we can succinctly write

$$
  \sigma(t) = \Gamma\left( (1-c) S_M a + S_N b \right)\, .
$$

### Misc

* Change $\alpha$ and $\omega$ to incorporate theory of planned behaviour?  Use logistic regression to get probability of compliance per capita, convert to rate (odds ratio?) and use this instead of alpha and omega.  In this setting, probably very much need different probabilities for each class.

* Can look at $I = I_N + I_M$ and $M = I_M + S_M + R_M$ and maybe work out some equilibriums?  First (wrong) solution thinks that

$$
  S_N = \frac{\gamma ( 1 + \frac{\omega}{\alpha})}{\beta(1 + (1-p)\frac{\omega}{\alpha})(1 + (1-c)\frac{\omega}{\alpha})}
$$

Problem is that $\omega$ and $\alpha$ depend on the disease states


# Improving the behaviour transitions

These are thoughts on how to improve the transition rates $\alpha$ and $\omega$ to be (in some sense) more realistic of human behaviour.  I found the paper "Incorporating human behaviour in simulation models of screening for breast cancer" (Brailsford et al., 2012) that builds a DES incorporating human behaviour models.  They argue that the theory of planned behaviour is the better model to implement because it nicely lends itself to mathematical modelling (through a logistic regression).  The also discuss the health belief model (preferred by Emily), but argue it is not clear how to model it because the relationships between the bubbles is not obvious.

My thought is to build a global behaviour logistic regression to replace $\alpha$ and $\omega$ with the probability of wearing as mask.  This will obviously be very coarse and run under many assumptions.  I am also not sure how to integrate the probability as a reasonable rate in the DE model.  Thoughts for each model are discussed below.

## The theory of planned behaviour

The theory of planned behaviour (Figure 1) is a cognitive-social behavioural model that predicts *intention* to perform a behaviour off of three main inputs:

1. **attitude towards behaviour**: This measures an individuals personal beliefs around how beneficial the behaviour is.  Theorised to be constructed of how beneficial the supposed outcomes of the behaviour is and how likely those outcomes are to occur.
2. **Subjective norms**:  This is the social influence, basically along the lines of "what do people I respect think of this behaviour?"
3. **Perceived behavioural control**:  This is the idea of "How well can I do this?  How much say to I have in this matter?"  This capture the "me" aspect of behaviour.

We can model the theory of planned behaviour in the following way.
Let $\pi_c$ be the probability that a randomly chosen individual in compartment $c \in \{S, I, R\}$ intends to wear a mask.  Let $X_1, X_2$ and $X_3$ denote scores reflecting their attitude towards the behaviour, subjective norms, and perceived behavioural control.  We model

\[
  \log\left( \frac{\pi_c}{1-\pi_c} \right) = \beta_0 + \beta_1 X_1 + \beta_2 X_2 + \beta_3 X_3\, .
\]

Then 

* $\beta_0$ measures the natural bias of the full population towards wearing a mask, i.e. if $\beta_0 < 0$ then people are more inclined to **not** wear masks
* $\beta_1$ measures the influence of a persons attitude towards a behaviour on them intending to do the behaviour
* $\beta_2$ measures the influence of subjective norms on performing the behaviour
* $\beta_3$ measures the influence of an individuals perceived control of the behaviour on their intention to perform it

Two issues arise in this model.  First, it predicts *intention* to perform the behaviour, which is approx $20\%$ predictive of actually performing the behaviour.  Second, this model does not account for past behaviour, as strong indicator of current behaviour.  Possible work arounds for this:

1. Build the uncertainty between intention and performance into the rate derived from $\pi_c$.
2. Expand the index set of $c$ to include the masked/non-masked components.

A final deficit of this model is that it does not include risk, which is going to be an important measure to account for in disease modelling.

### My thoughts to applying this to my model

I have tossed up some ideas of generalising my fear of disease and social influence into the theory of planned behaviour.  Based on the nature of the theory, the probability $\pi_c$ will be different depending on your compartment because what you deem important will change depending on your condition.  In the following, I am making the following assumptions (at least):

* Everyone is altruistic and rational
* Everyone has perfect knowledge of mask efficacy and disease prevalence
* Everyone knows the condition of the pope they mix with in a day
* At each time, individuals will make an independent decision on whether to wear a mask or not, i.e. the model is memoryless in knowledge of mask wearing.  Put another way, wearing a mask today has no effect on wearing a mask tomorrow.
* Everyone knows their own disease state

The measures I am currently considering are represented by survey-like questions below for each state.  Where possible, I have suggested the model parameters that will input into this.  (These concepts need to be discussed with Emily to assess suitability)

*Behavioural beliefs*

* **S** - wearing a mask will prevent me from catching the disease.  This is captured by the reduction in chance of catching the disease ($c$).
* **I** - wearing a mask will prevent me spreading the disease.  This is captured by the reduction in chance of spreading the disease ($p$)
* **S/I/R** - Wearing a mask will help convince others to do the same thing.

*Normative beliefs*

* **S/I/R** - Most people around me are wearing masks.  I suggest this be captured by the log odds of encountering someone wearing a mask ($\log(M/N)$).

*Perceived Control*

* **S/I/R** - I expect to have access to a mask (assumed constant)
* **S** - I expect to encounter people with the disease.  I am associating this to disease prevalence ($I$)
* **I** - I expect to encounter people without the disease.  I am associating this to the amount of people not with the disease ($1 - I$).


\begin{center}
\begin{figure}
\begin{tikzpicture}[node distance=2cm and 1cm,>=stealth',auto, every place/.style={draw}]

    \node[box] (att) [text width=3cm, align=center]{Attitude towards behaviour};
    \node[box] (subnorm) [below=of att, text width=3cm, align=center] {Subjective norms};
    \node[box] (pbc) [below=of subnorm, text width=3cm, align=center] {Perceived behavioural control};
    \node[box] (bintent) [right=of subnorm, align=center] {Behavioural intentions};
    \node[box, scale = 2] (behav) [right=of bintent, align=center] {Behaviour};
    
        
    \node[box] (belief_out) [left=of att, text width=4cm, align=center] {Belief about outcomes $\times$ Evaluation of outcomes};
    \node[box] (sub_input) [left=of subnorm, text width=4cm, align=center] {Normative beliefs $\times$ Motivation to comply};
    \node[box] (pbc_input) [left=of pbc, text width=4cm, align=center] {Perceived likelihood of occurance $\times$ Perceived facilitating or inhibiting power};
    
    
    
    
    \path[->] (att) edge node {} (bintent);
    \path[->] (subnorm) edge node {} (bintent);
    \path[->] (pbc) edge node {} (bintent);
    \path[->, dashed] (pbc) edge [bend right] node {} (behav);
    \path[->] (bintent) edge node {} (behav);
    
    \path[->] (belief_out) edge node {} (att);
    \path[->] (sub_input) edge node {} (subnorm);
    \path[->] (pbc_input) edge node {} (pbc);
    

\end{tikzpicture}
\caption{The theory of planned behaviour, from https://www.sciencedirect.com/science/article/pii/S0377221711009817}
\end{figure}
\end{center}

## The health belief model

- Durham2012 - Agent based model using HBM, masks and infectious diseases

The health belief model has gone through some renditions (Figure 2), but suggests that actions taken for health benefit are influenced by the following factors (Re. http://www.sbccimplementationkits.org/demandrmnch/wp-content/uploads/2014/02/Theory-at-a-Glance-A-Guide-For-Health-Promotion-Practice.pdf):

<!-- 1. **Health motivation**: TBD -->
1. **Self efficacy**: Confidence of one's ability to perform the behaviour
2. **Perception of illness threat**: This captures both perceived susceptibility to the illness and perceived severity of the illness.
    a. *Perceived susceptibility*: Belief about chance of getting disease
    b. *Perceived severity*: Beliefs about the seriousness of the condition and the consequences
3. **Evaluation of behaviours to counteract threat**: This captures the perceived benefits of the behaviour as well as the perceived barriers to performing the behaviour
    a. *Perceived Benefits*: Beliefs about the effectiveness of the behaviour to reduce seriousness
    b. *Perceived barriers*: Belief about material and psychological costs of taking the action
4. **Cues to action**: External or internal factors that activate the "readiness to change"

Durham and Casman includes the HBM in an agent-based model for disease spread to investigate the impact of behaviour on diseases spread, but decouples this from the epidemiology.  Durham and Casman focuses only on the second two inputs, investigating the sub-inputs to those drivers.  They suggest a fairly simply approach using a logistic regression in the following way.  Let $\pi_i$ be the probability that individual $i$ chooses to take up the behaviour.  Let $X_1, X_2, X_3$ and $X_4$ be an individuals binary indicators of low or high risk for susceptibility, severity, benefits, and barriers respectively.  They model
\[
  \log\left( \frac{\pi_i}{1 - \pi_i} \right) = \beta_0 + \beta_1 X_1 + \beta_2 X_2 + \beta_3 X_3 + \beta_4 X_4\, ,
\]
where

* $\beta_0$ is the baseline attitude towards the behaviour.
* $\beta_i$ is the effect of having a high risk value for measure $i$.

They actually present model with respect to odds ratios, but I find this a lot more opaque than the standard logistic regression format I am used to.

In their work, they suggest a cut off such that if $\hat\pi_i > 0.5$ at a given time for an agent, they will adopt the behaviour.  They also argue that $\beta_3 = 0$, that is, perceived benefit has no effect in their model, based off little correlation between the benefit and act of wearing a mask.  Further, they suggest models for $X_1, X_2$ and $X_4$ roughly based around the following:

* $X_1$ captures disease prevalence.  Measures the time dependant knowledge of disease today and in the past, with waning weight towards past cases.  Once this measure exceeds a threshold, they consider $X_1$ to be high risk.
* $X_2$ captures the fear of severity of the disease.  They suggest two possible models for this.  The first provides a ratio of deaths to infections as a measure of how sever it is.  The second measures the media coverage of the disease.  In both situations, once this fear exceeds a threshold, the $X_2$ variable is considered high.
* $X_4$ captures the social influence of the behaviour.  They argue that a barrier to mask wearing can be social stigma for wearing a mask when no one else is wearing one.  Thus, they give a weighted sum to observing those around you wearing a mask as an indicator for if you should wear one.  Again, they give this a threshold for it to tick over.  Due to the contradictory nature of a barrier, the barrier is considered low when many people are wearing a mask and high otherwise.

### My thoughts of applying this approach to my model

TBD

\begin{center}
\begin{figure}
\begin{tikzpicture}[node distance=2cm and 1cm,>=stealth',auto, every place/.style={draw}]

    \node[box] (selfefficacy) [text width=3cm, align=center] at (5.5, 6) {Self Efficacy};
    \node[box] (illnessthreat) [text width=3cm, align=center] at (3, 3) {Perception of illness threat};
    \node[box] (behaviours) [text width=3cm, align=center] at (3, -3) {Evaluation of behaviours to counteract threat};
    \node[box] (action) [text width=3cm, align=center] at (5.5, -6) {Cues to action};
    \node[box, scale = 2] (heatlhbehaviour) [text width=3cm, align=center] at (8, 0) {Health behaviour};
    
    
        
    \node[box] (suscep_ill) [text width=3cm, align=center] at (-2, 4.5) {Perceived susceptibility to illness};
    \node[box] (sever_ill) [text width=3cm, align=center] at (-2, 1.5) {Perceived severity of illness};
    \node[box] (benefit_in) [text width=3cm, align=center] at (-2, -1.5) {Perceived benefits of behaviour};
    \node[box] (barrier_in) [text width=3cm, align=center] at (-2, -4.5) {Perceived barriers to behaviour};
    
    \path[->] (selfefficacy) edge node {} (heatlhbehaviour);
    \path[->] (illnessthreat) edge node {} (heatlhbehaviour);
    \path[->] (behaviours) edge node {} (heatlhbehaviour);
    \path[->] (action) edge node {} (heatlhbehaviour);
    
    \path[->] (suscep_ill) edge node {} (illnessthreat);
    \path[->] (sever_ill) edge node {} (illnessthreat);
    \path[->] (benefit_in) edge node {} (behaviours);
    \path[->] (barrier_in) edge node {} (behaviours);
    

\end{tikzpicture}
\caption{The health belief model, from https://www.sciencedirect.com/science/article/pii/S0377221711009817}
\end{figure}
\end{center}

## Protection motivation theory

I have not had many thoughts on this one, but Emily has suggested it.  She also believes that they have untapped data relating to COVID and this theory.

\begin{center}
\begin{figure}
\begin{tikzpicture}[node distance=2cm and 1cm,>=stealth',auto, every place/.style={draw}]

    \node[positive] (intrinsic_reward) [text width=3cm, align=center] at (-0.5, 3) {Intrinsic reward};
    \node[positive] (extrinsic_reward) [text width=3cm, align=center] at (-0.5, 2) {Extrinsic reward};
    \node[positive] (resp_eff) [text width=3cm, align=center] at (-0.5, -2) {Response efficacy};
    \node[positive] (self_eff) [text width=3cm, align=center] at (-0.5, -3) {Self efficacy};
    
    \node[negative] (vuln) [text width=3cm, align=center] at (3.5, 3) {Perceived vulnerability};
    \node[negative] (sev) [text width=3cm, align=center] at (3.5, 2) {Perceived severity};
    \node[negative] (cost) [text width=3cm, align=center] at (3.5, -2.5) {Response cost};
    
    \node (threat) at (1.5, 4.25) {\textbf{Threat appraisal}};
    \node (coping) at (1.5, -0.75) {\textbf{Coping appraisal}};
    
    \node[box] (behav_intention) [text width=3cm, align=center] at (8, 0) {\textbf{Behaviour intention}};
    \node[box] (info) [text width=2.2cm, align=center] at (-5, 0) {\textbf{Context, Knowledge, Experience}};
    
    \draw[black,thick,dotted] ($(intrinsic_reward.north west)+(-0.3,0.6)$)  rectangle ($(sev.south east)+(0.3,-0.6)$);
    \draw[black,thick,dotted] ($(resp_eff.north west)+(-0.3,0.6)$)  rectangle ($(cost.south east)+(0.3,-0.8)$);
    
    \path[->] (info.south) edge [bend right=30] node {} ($(resp_eff.south west)+(-0.3,0)$);
    \path[->] (info.north) edge [bend left=30] node {} ($(intrinsic_reward.south west)+(-0.3,0)$);
    \path[<-] (behav_intention.north) edge [bend right=30] node {} ($(vuln.south east)+(0.3,0)$);
    \path[<-] (behav_intention.south) edge [bend left=30] node {} ($(cost.south east)+(0.3,0)$);
    

\end{tikzpicture}
\caption{The protection motivation theory, red is negative effect, green is positive effect. Version from \url{https://www.researchgate.net/figure/Schematic-presentation-of-the-Protection-Motivation-Theory-PMT-and-its-seven_fig1_267102412}}
\end{figure}
\end{center}

# A behaviour-infection model

Consider an influenza like illness governed by an $SIRS$ structure:

\begin{center}
\begin{tikzpicture}[node distance=2cm and 1cm,>=stealth',auto, every place/.style={draw}]
    
    \node [place] (Sn) [text width=0.75cm, align=center, below=of Sm] {$S$};
    \node [place] (In) [text width=0.75cm, align=center, below=of Im] {$I$};
    \node[place] (Rn) [text width=0.75cm, align=center, below=of Rm] {$R$};
    
    
    
    \path[->] (Sn) edge node {$\lambda(t)$} (In);
    \path[->] (In) edge node {$\gamma$} (Rn);
    \path[->] (Rn.north) edge [bend right=90, swap] node {$\nu$} (Sn.north);

\end{tikzpicture}
\end{center}

where

- $\lambda(t)$ is the force of infection;
- $1/\gamma$ is the average infection period;
- $1/\nu$ is the average immunity period, and;
- $S+I+R = P =1$.

Suppose we introduce a preventative health behaviour $B$ into the population that individuals can choose to take up.  We model this by stratifying the $S$, $I$, and $R$ components into $X_N$ and $X_B$, $X \in \{S, I, R\}$.  The strata $X_N$ represents those in the populations who are not performing the behaviour, and the strata $X_B$ represents those in the population who *are* performing the behaviour.  In fact, to capture radicals for each strata, we add further strata $X_{NN}$ and $X_{BB}$ of individuals who will never/always do the behaviour respectively.  Stratifying the population like this gives the following stratified SIRS model:

\begin{center}
\begin{tikzpicture}[node distance=2cm and 1cm,>=stealth',auto, every place/.style={draw}]
    
    \node [place] (Sm) [text width=0.75cm, align=center] {$S_{B}$};
    \node [place] (Smm) [text width=0.75cm, align=center, below=of Sm, yshift=1.5cm] {$S_{BB}$};
    \node [place] (Sn) [text width=0.75cm, align=center, above=of Sm] {$S_{N}$};
    \node [place] (Snn) [text width=0.75cm, align=center, above=of Sn, yshift=-1.5cm] {$S_{NN}$};
    \node [place] (Im) [text width=0.75cm, align=center, node distance=2.5cm,right=of Sm] {$I_B$};
    \node [place] (Imm) [text width=0.75cm, align=center, node distance=2.5cm,right=of Smm] {$I_{BB}$};
    \node [place] (In) [text width=0.75cm, align=center, above=of Im] {$I_{N}$};
    \node [place] (Inn) [text width=0.75cm, align=center, above=of In, yshift=-1.5cm] {$I_{NN}$};
    \node[place] (Rm) [text width=0.75cm, align=center, node distance=2.5cm, right=of Im] {$R_B$};
    \node[place] (Rmm) [text width=0.75cm, align=center, node distance=2.5cm, right=of Imm] {$R_{BB}$};
    \node[place] (Rn) [text width=0.75cm, align=center, above=of Rm] {$R_N$};
    \node[place] (Rnn) [text width=0.75cm, align=center, above=of Rn, yshift=-1.5cm] {$R_{NN}$};
    
    \draw[green,thick,dotted] ($(Sm.north west)+(-0.3,0.6)$)  rectangle ($(Rmm.south east)+(0.3,-0.6)$);
    \draw[red,thick,dotted] ($(Snn.north west)+(-0.3,0.6)$)  rectangle ($(Rn.south east)+(0.3,-0.6)$);
    
    \node[green] (masks) at ($(Rmm.south east)+(1.5,-0.6)$) {\textbf{Behaviour}};
    \node[red] (nomasks) at ($(Rnn.north east)+(1.8,0.6)$) {\textbf{No Behaviour}};
    
    
    \path[->] (Sm) edge [bend left] node {$\alpha(t)$} (Sn);
    \path[->] (Sn) edge [bend left] node {$\omega(t)$} (Sm);
    \path[->] (Im) edge [bend left] node {$\alpha(t)$} (In);
    \path[->] (In) edge [bend left] node {$\omega(t)$} (Im);
    \path[->] (Rm) edge [bend left] node {$\alpha(t)$} (Rn);
    \path[->] (Rn) edge [bend left] node {$\omega(t)$} (Rm);
    
    \path[->] (Sm) edge node {$\lambda(t)$} (Im);
    \path[->] (Smm) edge node {$\lambda(t)$} (Imm);
    \path[->] (Sn) edge node {$\lambda(t)$} (In);
    \path[->] (Snn) edge node {$\lambda(t)$} (Inn);
    \path[->] (In) edge node {$\gamma$} (Rn);
    \path[->] (Inn) edge node {$\gamma$} (Rnn);
    \path[->] (Im) edge node {$\gamma$} (Rm);
    \path[->] (Imm) edge node {$\gamma$} (Rmm);
    \path[->] (Rn) edge node {$\nu$} ($(Rn.east)+(1,0)$);
    \path[->] (Rnn) edge node {$\nu$} ($(Rnn.east)+(1,0)$);
    \path[->] (Rm) edge node {$\nu$} ($(Rm.east)+(1,0)$);
    \path[->] (Rmm) edge node {$\nu$} ($(Rmm.east)+(1,0)$);
    \path[->] ($(Sn.west)+(-1,0)$) edge node {$\nu$} (Sn);
    \path[->] ($(Snn.west)+(-1,0)$) edge node {$\nu$} (Snn);
    \path[->] ($(Sm.west)+(-1,0)$) edge node {$\nu$} (Sm);
    \path[->] ($(Smm.west)+(-1,0)$) edge node {$\nu$} (Smm);

\end{tikzpicture}
\end{center}

where:

- $\lambda(t), \gamma$, and $\nu$ are as above for the $SIRS$ model;
- $\omega(t)$ is the rate someone in strata $N$ *takes up* the behaviour $B$;
- $\alpha(t)$ is the rate someone in strata $B$ *gives up* the behaviour $B$;
- To simplify the model, we have assumed $\omega(t)$ and $\alpha(t)$ are the same across disease states $S, I, R$, and;
- $1=P = \sum_{X \in \{S,I,R\}} (X_{N} + X_{NN} + X_{B} + X_{BB})$.

Notice how the radical groups $X_{NN}$ and $X_{BB}$ are "immune" to the behavioural changes $\omega(t)$ and $\alpha(t)$.  However, this model does preclude the idea that an individual can become radicalised to a behaviour, or a radical may become less radical.

Assuming homogeneous mixing of the population, we propose the frequency dependent (noting everything is in proportions) force of infection give by

\[
  \lambda(t) = \beta\left( (I_N + I_{NN}) + (1-p)(I_B + I_{BB}) \right)\, ,
\]

where 

- $\beta$ contains information on the average contact rate and probability of infection, and;
- $p\times 100\%$ is the decrease in infectiousness due to the behaviour $B$.  In other words, $p$ describes how effective the behaviour $B$ is at reducing the infectiousness of an individual.

Assuming there is a parameter $c$ that describes how effective the behaviour $B$ is at reducing an individuals *susceptibility*, we may write the following set of differential equations to describe our model:

- $NN$
\[
  \begin{cases}
    \dot{S}_{NN} &= -\lambda(t)  S_{NN} + \nu R_{NN}\\ 
    \dot{I}_{NN} &= \lambda(t)  S_{NN} -\gamma I_{NN}\\ 
    \dot{R}_{NN} &= \gamma I_{NN} -  \nu R_{NN}
  \end{cases}
\]
- $N$
\[
  \begin{cases}
    \dot{S}_{N} & =  -\lambda(t) S_{N} + \alpha(t) S_{B} - \omega(t) S_{N} + \nu R_N\\
    \dot{I}_{N} & = \lambda(t) S_{N} + \alpha(t) I_{B} - \omega(t) I_{N} - \gamma I_{N}\\
    \dot{R}_N & = \gamma I_{N} + \alpha(t) R_{B} - \omega(t) R_{N} - \nu R_N \, ,
  \end{cases}
\]
- $B$
\[
  \begin{cases}
    \dot{S}_{B} & =  -\lambda(t) (1-c) S_{B} - \alpha(t) S_{B} + \omega(t) S_{N} + \nu R_B\\
    \dot{I}_{B} & = \lambda(t) (1-c) S_{B} - \alpha(t) I_{B} + \omega(t) I_{N} - \gamma I_{B}\\
    \dot{R}_B & = \gamma I_{B}  - \alpha(t) R_{B} + \omega(t) R_{N} - \nu R_B\, \\
  \end{cases}
\]
- $BB$
\[
  \begin{cases}
    \dot{S}_{BB} &= -\lambda(t) (1-c) S_{BB} + \nu R_{BB}\\ 
    \dot{I}_{BB} &= \lambda(t) (1-c) S_{BB} -\gamma I_{BB}\\ 
    \dot{R}_{BB} &= \gamma I_{BB} -  \nu R_{BB}
  \end{cases}
\]

where the dot represents the derivative with respect to time.  When we wish to discuss the *behavioural states* (red/green rectangles in state diagram) of the model, we will commonly write

- $N = S_{N} + S_{NN} + I_{N} + I_{NN} + R_{N} + R_{NN}$, and;
- $B = S_{B} + S_{BB} + I_{B} + I_{BB} + R_{B} + R_{BB}$.

Note then that $N + B = 1$ and we find that

- $\dot{N} = -\omega(t) (S_{N} + I_N + R_N) + \alpha(t) (S_B + I_B + R_B)$, and;
- $\dot{B} = \omega(t) (S_{N} + I_N + R_N) - \alpha(t) (S_B + I_B + R_B)$.

This demonstrates that we have an $SIS$-like structure on our behaviour in the sense that "susceptible" individuals ($N$) can become "infected" with the behaviour ($B$) and eventually "recover" back to "susceptible".

### Using behavioural models to describe $\omega$ and $\alpha$

To determine the uptake ($\omega$) and the upkeep ($\alpha$) of the behaviour $B$, we propose using the health belief model (Figure 2).  The health belief model is a popular behavioural science model that aims to explain why an individual chooses to follow a behaviour that can be directly beneficial for their health (such as wearing a mask or getting vaccinated).  The health belief model is made up of six inputs, so it is reasonable to write

\[
  \omega(t) = w_1(t) + w_2(t) + w_3(t) + w_4(t) + w_5(t) + w_6(t)\, ,
\]
where

- $w_1(t)$ represents the influence of perceived susceptibility to the disease on performing the behaviour
- $w_2(t)$ represents the influence of perceived severity of the disease on performing the behaviour
- $w_3(t)$ represents the influence of perceived benefits of the behaviour on performing the behaviour
- $w_4(t)$ represents the influence of perceived barriers to the behaviour on performing the behaviour
- $w_5(t)$ represents the influence of cues to action on performing the behaviour
- $w_6(t)$ represents the influence of self efficacy on performing the behaviour

The functional forms of $w_i(t)$, $i = 1, 2, \dots, 6$, can be highly complex and depend both on the behaviour and the specific pathogen.  For example, if the behaviour is getting a vaccine, we may expect $w_4(t)$ to be (negatively) large due to general fear and possible side effects of the vaccine.  However, if the pathogen has a high mortality rate we may expect the effect of $w_2(t)$ to be (positively) large.  As a general rule to avoid parameter blow out, we suggest to parameterise each $w_i$ around the disease states ($S, I, R$), the behaviour states ($N, B$), the model parameters ($\beta, \gamma, \nu, p, c$), and time ($t$).

In a similar manner, we may write

\[
  \alpha(t) = a_1(t) + a_2(t) + a_3(t) + a_4(t) + a_5(t) + a_6(t)\, ,
\]

where each $a_i$ now describes the influence of the components of the HBM in *maintaining* the health behaviour $B$.  For example, $a_1(t)$ describes the influence of the perceived susceptibility of the disease on an individuals ability to continue performing a behaviour.  Once again these are very behaviour and disease dependant.  Taking the example of vaccination as the behaviour, we note this is not a behaviour that someone can simply "stop doing". In such a situation, many components of $\alpha(t)$ would be identically zero.

### Behavioural model for mask wearing

Suppose our behaviour $B$ is the act of wearing a mask.  We consider the following parameterisation for uptake of mask wearing ($\omega(t)$):

1. $w_1(t) \propto I(t) = I_{N}(t) + I_{NN}(t) + I_{B}(t) + I_{BB}(t)$.  This assumes that each individual in the $N$ population is instantaneously aware of the exact prevalence of the disease at time $t$.
2. $w_2(t) \propto \sigma I(t)$, where $\sigma$ is the (assumed constant) proportion of infected people who get sever cases of the disease (hospitalisation or death).  Assuming a mild pathogen, we take $w_2(t) \approx 0$.
3. $w_3(t) = f(p, c)$, where $f$ is a function describing the public perception of mask efficacy for both susceptible and infected individuals.  Assuming (on average) little knowledge of the efficacy of masks for each individual, we take $f(p, c) =$ constant.
4. $w_4(t) \approx 0$.  We assume everyone has access to affordable mask options.
5. $w_5(t) \propto B +$constant.  We consider the cues to action of wearing a mask to be described by the amount of people you see around you wearing a mask, as well as a constant source due to government advertising and signage.
6. $w_6(t) \approx$ constant.  We take self efficacy to be (on average) constant across the population as wearing a mask is a relatively low-effort behaviour.

Combining these assumptions, we write

\[
  \omega(t) = \omega_1 B(t) + \omega_2 I(t) + \omega_3
\]

where $\omega_1, \omega_2, \omega_3$ are all positive constants.

In a similar manner we can build up the functional form for *dropping* the behaviour of mask wearing.  We suggest

1. $a_1(t) \propto 1 - I(t)$.  This assumes someone doing the behaviour assess their susceptibility by how many people in the population are *not* infected.  This should capture the idea that many people seems to ignore that the behaviour is directly related to the reduction of infected peoples in the community.  Note that since $1-I \gg I$ (in general), the constant of proportionality should be appropriately small to avoid a "flooding effect".
2. $a_2(t) \propto \sigma I(t)$.  However, as before we assume a mild pathogen such that $a_2(t) \approx 0$.
3. $a_3(t) = g(p, c)$, where $g$ is a function describing the public perception of mask efficacy for both susceptible and infected individuals.  Assuming (on average) little knowledge of the efficacy of masks for each individual, we take $g(p, c) =$ constant.
4. $a_4(t) \approx 0$.  We assume there are little to no barriers for continued mask wearing.
5. $a_5(t) \propto N +$constant.  We need to consider the cues to action for an individual to **stop** wearing a mask.  We take this to be social cues of other individuals not wearing masks ($N$) as well as an "exhaustion" effect, which is an internal cue to action we capture through a constant.
6. $a_6(t)\approx$ constant. We take the self efficacy of maintaining the behaviour of mask wearing as constant.

As with $\omega(t)$, we may write

\[
  \alpha(t) = \alpha_1 N(t) + \alpha_2 (1 - I(t)) + \alpha_3\, ,
\]

where $\alpha_1, \alpha_2, \alpha_3$ are all positive constants.

#### Notes

1. Assume that radicals are negligible for mask wearing, such that $BB \approx NN \approx 0$.  This simplifies the model.
2. Look over short time span (more reasonable for masks?) so take $\nu = 0$.
3. Calculate R-effective using NGM
4. Calculate equilibrium of behaviour
5. If possible, final size of disease (is the behaviour useful?)
    a. Very likely no analytic or semi analytic form

### Behavioural model for vaccination

Suppose the behaviour $B$ is the behaviour of getting vaccinated.  We build the functional form $\omega(t)$ as follows:

1. $w_1(t) \propto I(t)$.  This assumes that each individual in the $N$ population is instantaneously aware of the exact prevalence of the disease at time $t$.
2. $w_2(t) \propto \sigma I(t)$, where $\sigma$ is the (assumed constant) proportion of infected people who get sever cases of the disease (hospitalisation or death).  Assuming a moderately high mortality rate, we consider $w_2(t) \neq 0$.
3. $w_3(t) = f(p, c) + \sigma_N (I_N(t) + I_{NN}(t)) / \sigma_BI_B(t)$, where $f$ is a function describing the public perception of vaccination efficacy for both susceptible and infected individuals and $\sigma_N$ and $\sigma_B$ describe the mortality rates of non-vaccinated and vaccinated peoples respectively.  Assuming (on average) little knowledge of the true efficacy of vaccination for each individual, we take $f(p, c) =$ constant.
4. $w_4(t) \propto NN +$ constant.  This assumes the vocal "anti-vax" group may affect the uptake of a vaccination program, and the constant represents individual hesitancy and fear of possible side-effects of the vaccine.
5. $w_5(t) \propto \sigma_N (I_N(t) + I_{NN}(t)) +$constant.  We consider the cues to action of wearing a mask to be described by the amount of unvaccinated people getting sever illness, as well as a constant source due to government advertising and signage.  Note that vaccination is not a visible behaviour, so the proportion of people vaccinated will not affect the number of people to take up vaccination.
6. $w_6(t) \approx$ constant.  We take self efficacy to be (on average) constant across the population.

This creates the functional form

\[
  \omega(t) = \omega_1(1 + \sigma) I(t) + \omega_2\sigma_N (I_{N}(t) + I_{NN}(t))(1 + 1/(\sigma_B I_B(t) + \varepsilon)) - \omega_3NN(t) + \omega_4.
\]

Note that we have included the $\varepsilon \ll 1$ term to prevent dividing by zero.  Note that although $\omega_1, \omega_2, \omega_3, \omega_4$ are all positive constants, they are constrained such that $\omega(t) \geq 0$ for all time $t$.  ***As a note, we could extend this such that if $\omega(t) < 0$ people transition from $N$ to $NN$.***

Now consider the "dropping of behaviour" $\alpha(t)$.  Vaccination is not a behaviour that can be stopped as once you are vaccinated there is no going back.  We could consider a two-step behaviour that captures "partial vaccination" and "full vaccination," but for simplicity we will assume one vaccination does is enough for full coverage.  However, although we take $a_1(t) = a_2(t) = a_3(t) = a_4(t) = a_5(t)$, we do consider $a_6(t) = \alpha$, a positive constant.  We take the "self efficacy of maintaining vaccination status" to be described by the longevity of the vaccine coverage.  As such, 
$$
\alpha(t) = \alpha
$$
and we can interpret $1/\alpha$ as the average time that an individual remains effectively vaccinated before returning to "unvaccinated" status.



#### Notes

1. Assume that radicals are negligible for getting vaxxed, but vocal for not getting vaxxed.  i.e. take $BB \approx 0$ and $NN >0$.
2. Look over long time span (so we can consider vaccine wear off) so take $\nu > 0$.
3. Calculate R-effective using NGM?
4. Calculate equilibrium of behaviour?
5. If possible, steady state of disease (is the behaviour useful?)
    a. Very likely no analytic or semi analytic form    
    
## The "behavioural R0"

I want to think about how "infectious" our behaviour is in the mask setting.  Consider the behavioural transition equation:

\[
  \dot{B} = (\omega_1 B + \omega_2 I + \omega_3) N - (\alpha_1N + \alpha_2(1 - I) + \alpha_3) B\, .
\]

In the "disease and behaviour free equilibrium" we have that $N= 1$ and $1-I = 1$, so for small $t$ (and small $I$ and $B$) we get the linearised version

\[
  \dot{B} = \omega_1 B + \omega_2 I + \omega_3 - (\alpha_1 + \alpha_2 + \alpha_3) B\, .
\]

I have tried to do a few different things here, but keep getting stuck.  I have tried:

1. Calculating the NGM in the usual way
2. Calculating the "NGM with large domain" circa Roberts2010 (https://royalsocietypublishing.org/doi/full/10.1098/rsif.2009.0386)
3. Straight up reasoning it out.

If $\omega_3 = 0$, I want to say the following.  We have that

<!-- \[ -->
<!--   \begin{aligned} -->
<!--     R_0^B & = \frac{\omega_1 + \omega_2}{\alpha_1 + \alpha_2 + \alpha_3} \\    -->
<!--       & = \frac{\omega_1}{\alpha_1 + \alpha_2 + \alpha_3} + \frac{\omega_2}{\alpha_1 + \alpha_2 + \alpha_3} \\ -->
<!--       & = R_0^{B\rightarrow B} + R_0^{I\rightarrow B}\, . -->
<!--   \end{aligned} -->
<!-- \] -->
\[
  \begin{aligned}
    R_0^B & = \frac{\omega_1}{\alpha_1 + \alpha_2 + \alpha_3} + \frac{\omega_2}{\gamma} \\
      & = R_0^{B\rightarrow B} + R_0^{I\rightarrow B}\, .
  \end{aligned}
\]

This seems to hold, but I can't derive this nicely.  I also cannot reconcile $\omega_3$ into any arguments for $R_0^B$.  I also feel like the disease parameters $\gamma$ and $\beta$ should play into this.